# Generated by Django 5.1.6 on 2025-03-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='related_account',
        ),
    ]
