# Generated by Django 5.1.6 on 2025-03-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('S', 'Savings'), ('C', 'Current'), ('F', 'Fixed Deposit')], max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('S', 'Savings'), ('C', 'Current'), ('F', 'Fixed Deposit')], max_length=1)),
                ('initial_deposit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
